# Generated by Django 3.0.3 on 2020-04-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Mobile', models.IntegerField()),
                ('Address', models.TextField(max_length=100)),
                ('Gender', models.CharField(max_length=20)),
                ('Hobbies', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Country', models.CharField(max_length=50)),
                ('File', models.ImageField(upload_to='')),
            ],
        ),
    ]
